### ISSUE TITLE
iina wiki svp

### ISSUE THREAD

**Issue by HarukaMa** [HarukaMa/image-repo#1]
![screen shot 2017-08-03 at 15 41 41](https://user-images.githubusercontent.com/861659/28937039-864eb400-78c4-11e7-84b7-f90bdbed77e7.png)
![screen shot 2017-08-04 at 2 56 01](https://user-images.githubusercontent.com/861659/28937057-9a6a3090-78c4-11e7-939c-371344156420.png)
![screen shot 2017-08-04 at 2 58 49](https://user-images.githubusercontent.com/861659/28937060-9c119230-78c4-11e7-8e43-6fdcf9fc1c88.png)
![screen shot 2017-08-04 at 3 04 23](https://user-images.githubusercontent.com/861659/28937067-a4b72a80-78c4-11e7-930f-6105191f0b2f.png)
![screen shot 2017-08-04 at 2 04 17](https://user-images.githubusercontent.com/861659/28937071-a898c276-78c4-11e7-87fe-81303995a3b6.png)

**Comment by HarukaMa** [comment]
![2017-08-04 04 42 01](https://user-images.githubusercontent.com/861659/28940885-1f746998-78d1-11e7-8e1d-513f77148fa6.png)
![2017-08-04 04 47 19](https://user-images.githubusercontent.com/861659/28940889-2592be38-78d1-11e7-837a-7f2fc000185b.png)
![2017-08-04 04 57 13](https://user-images.githubusercontent.com/861659/28940967-661943d2-78d1-11e7-86f2-b9b54224e018.png)
![2017-08-04 04 53 24](https://user-images.githubusercontent.com/861659/28940903-32112172-78d1-11e7-9524-2d0c772ddaa2.png)

**Comment by StV0911** [comment]
@HarukaMa 
thank you for this very helpfull Instruction.
I know that to get iina working with svp we have to remove libmpv*.dylib in IINA.app/Frameworks.
SVP i working very well with IINA but after removing the dylib, IINA can not show preview thumbnails.
I tested it several times, also mentioned it on telegram.. I know that collider li and you and all the people have a lot to do with the dev. of Iina, i just like to ask you if you know a workaround so that thumbnails preview works also after removing the dylib.
Thanks
Gr.
StV0911
